// https://github.com/valitydev/bouncer-policies/blob/master/policies/service/authz/roles/data.yaml
export const ROLES = {
    Integrator: {
        apis: {
            CommonAPI: {
                operations: [
                    'GetShops',
                    'GetShopsForParty',
                    'GetMyParty',
                    'GetPartyByID',
                    'GetInvoiceByID',
                    'GetPayments',
                    'GetPaymentByID',
                    'CreateWebhook',
                    'GetWebhooks',
                    'GetWebhooksForParty',
                    'GetWebhookByID',
                    'DeleteWebhookByID',
                ],
            },
            OrgManagement: {
                operations: [
                    'getOrg',
                    'getOrgRole',
                    'getOrgMember',
                    'cancelOrgMembership',
                    'inquireOrgMembership',
                    'listOrgMembership',
                    'switchContext',
                ],
            },
            ApiKeyMgmt: {
                operations: ['GetApiKey', 'ListApiKeys'],
            },
            AnalyticsAPI: {
                operations: [
                    'SearchInvoices',
                    'SearchPayments',
                    'SearchRefunds',
                    'SearchInvoiceTemplates',
                ],
            },
        },
    },
    WalletManager: {
        apis: {
            WalletAPI: {
                operations: [
                    'ListWallets',
                    'GetWallet',
                    'GetWalletByExternalID',
                    'GetWalletAccount',
                    'GetWalletCashLimits',
                    'ListDestinations',
                    'GetDestination',
                    'GetDestinationByExternalID',
                    'CreateDestination',
                    'CreateQuote',
                    'CreateWithdrawal',
                    'GetWithdrawal',
                    'GetWithdrawalByExternalID',
                    'ListWithdrawals',
                    'PollWithdrawalEvents',
                    'GetWithdrawalEvents',
                    'ListDeposits',
                    'CreateWebhook',
                    'GetWebhooks',
                    'GetWebhookByID',
                    'DeleteWebhookByID',
                    'CreateReport',
                    'GetReport',
                    'GetReports',
                    'DownloadFile',
                    'StoreBankCard',
                    'GetBankCard',
                ],
            },
            OrgManagement: {
                operations: [
                    'getOrg',
                    'getOrgRole',
                    'getOrgMember',
                    'cancelOrgMembership',
                    'inquireOrgMembership',
                    'listOrgMembership',
                    'switchContext',
                ],
            },
        },
    },
    Accountant: {
        apis: {
            CommonAPI: {
                operations: [
                    'GetMyParty',
                    'GetPartyByID',
                    'GetInvoiceByID',
                    'GetPayments',
                    'GetPaymentByID',
                    'CreateRefund',
                    'GetShops',
                    'GetShopsForParty',
                    'GetRefunds',
                    'GetRefundByID',
                ],
            },
            OrgManagement: {
                operations: ['getOrg', 'getOrgMember', 'cancelOrgMembership', 'switchContext'],
            },
            AnalyticsAPI: {
                operations: [
                    'SearchInvoices',
                    'SearchPayments',
                    'SearchRefunds',
                    'SearchReports',
                    'SearchInvoiceTemplates',
                    'GetReport',
                    'CreateReport',
                    'CancelReport',
                    'DownloadFile',
                ],
            },
        },
    },
    Manager: {
        apis: {
            CommonAPI: {
                operations: [
                    'CreateInvoiceTemplate',
                    'GetInvoicePaymentMethodsByTemplateID',
                    'CreateInvoice',
                    'GetInvoiceByID',
                    'FulfillInvoice',
                    'RescindInvoice',
                    'GetInvoicePaymentMethods',
                    'GetShops',
                    'GetShopsForParty',
                    'GetMyParty',
                    'GetPartyByID',
                    'GetPayments',
                    'GetPaymentByID',
                    'CreateCustomer',
                    'GetCustomerByID',
                    'GetCustomerByExternalID',
                    'CreateCustomerAccessToken',
                    'GetCustomerPayments',
                    'GetCustomerBankCards',
                    'InspectUser',
                ],
            },
            OrgManagement: {
                operations: [
                    'getOrg',
                    'getOrgRole',
                    'getOrgMember',
                    'cancelOrgMembership',
                    'inquireOrgMembership',
                    'listOrgMembership',
                    'switchContext',
                ],
            },
            AnalyticsAPI: {
                operations: [
                    'SearchInvoices',
                    'SearchPayments',
                    'SearchRefunds',
                    'SearchInvoiceTemplates',
                    'GetPaymentsToolDistribution',
                    'GetPaymentsAmount',
                    'GetAveragePayment',
                    'GetPaymentsCount',
                    'GetPaymentsErrorDistribution',
                    'GetPaymentsSplitAmount',
                    'GetPaymentsSplitCount',
                    'GetRefundsAmount',
                    'GetCurrentBalances',
                    'GetPaymentsSubErrorDistribution',
                    'GetCurrentBalancesGroupByShop',
                    'GetCreditingsAmount',
                    'GetCurrentShopBalances',
                ],
            },
        },
    },
    Administrator: {
        apis: {
            CommonAPI: {
                operations: [
                    'GetContracts',
                    'GetContractByID',
                    'GetContractAdjustments',
                    'GetContractAdjustmentByID',
                    'GetContractsForParty',
                    'GetContractByIDForParty',
                    'GetContractAdjustmentsForParty',
                    'GetContractAdjustmentByIDForParty',
                    'CreateInvoiceTemplate',
                    'GetInvoiceTemplateByID',
                    'UpdateInvoiceTemplate',
                    'DeleteInvoiceTemplate',
                    'CreateInvoiceWithTemplate',
                    'GetInvoicePaymentMethodsByTemplateID',
                    'CreateInvoice',
                    'CreateInvoiceAccessToken',
                    'CreateInvoiceUrl',
                    'GetInvoiceByID',
                    'GetInvoiceByExternalID',
                    'GetInvoiceByExternalIDForParty',
                    'FulfillInvoice',
                    'RescindInvoice',
                    'GetInvoiceEvents',
                    'GetInvoicePaymentMethods',
                    'GetMyParty',
                    'GetPartyByID',
                    'ActivateMyParty',
                    'SuspendMyParty',
                    'CreatePayment',
                    'GetPayments',
                    'GetPaymentByID',
                    'GetRefundByExternalID',
                    'GetRefundByExternalIDForParty',
                    'GetPaymentByExternalID',
                    'GetPaymentByExternalIDForParty',
                    'CancelPayment',
                    'CapturePayment',
                    'CreateRefund',
                    'GetRefunds',
                    'GetRefundByID',
                    'GetChargebacks',
                    'GetChargebackByID',
                    'SearchInvoices',
                    'SearchPayments',
                    'SearchRefunds',
                    'ActivateShop',
                    'SuspendShop',
                    'GetShops',
                    'GetShopByID',
                    'GetShopsForParty',
                    'GetShopByIDForParty',
                    'GetShopCashLimitsForParty',
                    'ActivateShopForParty',
                    'SuspendShopForParty',
                    'CreateWebhook',
                    'GetWebhooks',
                    'GetWebhooksForParty',
                    'GetWebhookByID',
                    'DeleteWebhookByID',
                    'CreateCustomer',
                    'GetCustomerByExternalID',
                    'GetCustomerByID',
                    'DeleteCustomer',
                    'CreateCustomerAccessToken',
                    'GetCustomerPayments',
                    'GetCustomerBankCards',
                    'InspectUser',
                ],
            },
            OrgManagement: {
                operations: [
                    'listInvitations',
                    'createInvitation',
                    'getInvitation',
                    'revokeInvitation',
                    'getOrgMember',
                    'listOrgMembers',
                    'listOrgRoles',
                    'patchOrg',
                    'assignMemberRole',
                    'expelOrgMember',
                    'removeMemberRole',
                    'getOrg',
                    'getOrgRole',
                    'cancelOrgMembership',
                    'inquireOrgMembership',
                    'listOrgMembership',
                    'switchContext',
                ],
            },
            ApiKeyMgmt: {
                operations: [
                    'GetApiKey',
                    'RevokeApiKey',
                    'RequestRevokeApiKey',
                    'ListApiKeys',
                    'IssueApiKey',
                ],
            },
            ClaimManagement: {
                operations: [
                    'createClaim',
                    'revokeClaimByID',
                    'requestReviewClaimByID',
                    'updateClaimByID',
                ],
            },
            AnalyticsAPI: {
                operations: [
                    'SearchInvoices',
                    'SearchPayments',
                    'SearchRefunds',
                    'SearchReports',
                    'SearchChargebacks',
                    'SearchInvoiceTemplates',
                    'GetReport',
                    'CreateReport',
                    'CancelReport',
                    'DownloadFile',
                    'GetPaymentsToolDistribution',
                    'GetPaymentsAmount',
                    'GetAveragePayment',
                    'GetPaymentsCount',
                    'GetPaymentsErrorDistribution',
                    'GetPaymentsSplitAmount',
                    'GetPaymentsSplitCount',
                    'GetRefundsAmount',
                    'GetCurrentBalances',
                    'GetPaymentsSubErrorDistribution',
                    'GetCurrentBalancesGroupByShop',
                    'GetCreditingsAmount',
                    'GetCurrentShopBalances',
                ],
            },
            WalletAPI: {
                operations: [
                    'ListWallets',
                    'GetWallet',
                    'GetWalletByExternalID',
                    'GetWalletAccount',
                    'GetWalletCashLimits',
                    'ListDestinations',
                    'GetDestination',
                    'GetDestinationByExternalID',
                    'CreateDestination',
                    'CreateQuote',
                    'CreateWithdrawal',
                    'GetWithdrawal',
                    'GetWithdrawalByExternalID',
                    'ListWithdrawals',
                    'PollWithdrawalEvents',
                    'GetWithdrawalEvents',
                    'ListDeposits',
                    'CreateWebhook',
                    'GetWebhooks',
                    'GetWebhookByID',
                    'DeleteWebhookByID',
                    'CreateReport',
                    'GetReport',
                    'GetReports',
                    'DownloadFile',
                    'StoreBankCard',
                    'GetBankCard',
                ],
            },
        },
    },
};
