name: Init
description: Init
runs:
    using: composite
    steps:
        - name: Init Thrift
          uses: valitydev/action-setup-thrift@v0.0.1

        - name: Init NodeJS
          uses: actions/setup-node@v2
          with:
              node-version: '16.4.2'
              cache: 'npm'

        - name: Install Packages
          run: npm ci
          shell: bash

        - name: Compile Thrift
          run: npm run compile
          shell: bash
