name: Init
description: Init
runs:
    using: composite
    steps:
        - uses: valitydev/action-frontend/setup@v0.1
        - uses: valitydev/action-setup-thrift@v1.0.0
        - run: npm ci
          shell: bash
        - name: Compile Thrift
          run: npm run compile
          shell: bash
