name: Init
description: Init
runs:
  using: composite
  steps:
    - uses: valitydev/action-frontend/setup@v1
    # TODO: Need to remove `--force` after removing deprecated `@angular/flex-layout`
    - run: npm ci --force
      shell: bash
