name: Build & Push
on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
    branches: ["*"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout GitHub Action Deploy Docker Repo
        uses: actions/checkout@v2
        with:
          repository: valitydev/action-deploy-docker
          ref: v1.0.16
          path: .github/actions/action-deploy-docker

      - name: Init
        uses: ./.github/actions/init

      - name: Deploy image
        uses: ./.github/actions/action-deploy-docker
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}