name: Build 2
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'
          cache: 'npm'
      - name: Init Thrift
        uses: valitydev/action-setup-thrift@v0.0.1
      - name: Install Packages
        run: npm ci
      - name: Compile Thrift
        run: npm run compile
      - uses: actions/cache@v2
        id: restore-init
        with:
          path: ./*
          key: ${{ github.sha }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'
          cache: 'npm'
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Build
        run: npm run build

  check:
    name: Check
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'
          cache: 'npm'
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Check
        run: concurrently --kill-others-on-fail --prefix-colors magenta,green --names PRETTIER,LINT "npm run prettier" "npm run lint-errors"