name: Main
on:
  push:
    branches: ['master', 'main', 'epic/*']

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: valitydev/action-frontend/setup-install@v3
        with:
          release: true
      - name: Build
        run: npm run build
      - name: Deploy image
        uses: valitydev/action-deploy-docker@v2
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build MatEz Library
        run: npm run build -- matez
      - name: Publish MatEz Library
        uses: valitydev/action-frontend/publish@v3
        with:
          directory: ./dist/matez
      - name: Notify Mattermost
        uses: valitydev/action-mattermost-notify@v0
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: 'control-center'
          username: 'Frontend'
