name: Main
on:
  push:
    branches: ['master', 'main', 'epic/*']
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-frontend/setup-install@v2
      - name: Build
        run: npm run build
      - name: Deploy image
        uses: valitydev/action-deploy-docker@v2
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.GITHUB_TOKEN }}
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [deploy]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-mattermost-notify@v0.1.4
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: 'control-center-improvements'
          username: 'Frontend'
