name: Main
on:
    push:
        branches: ['master', 'main']
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/init
            - name: Check & Build
              run: npm run ci:build
            - name: Deploy image
              uses: valitydev/action-deploy-docker@v1.0.16
              with:
                  registry-username: ${{ github.actor }}
                  registry-access-token: ${{ secrets.GITHUB_TOKEN }}
                  dockerfile-path: .
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
