name: Main
on:
  push:
    branches: ['master', 'main', 'epic/**']
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Build
        run: npm run build
      - name: Deploy image
        uses: valitydev/action-deploy-docker@v2
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: set config
        run: |
          printf "$APP_ENV_FILE" > dist/control-center/assets/appConfig.json
          printf "$AUTH_ENV_FILE" > dist/control-center/assets/authConfig.json
        env:
          APP_ENV_FILE: ${{secrets.APP_CONF}}
          AUTH_ENV_FILE: ${{secrets.AUTH_CONF}}
      - name: Publish to CF Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'cc'
          directory: 'dist/control-center'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-mattermost-notify@v0.1.4
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: 'frontend-deployments'
          username: 'Frontend'
      - uses: valitydev/action-mattermost-notify@v0.1.4
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: 'control-center-improvements'
          username: 'Frontend'
