name: Main
on:
  push:
    branches: ['master', 'main', 'epic/*']

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: valitydev/action-frontend/setup-install@v3
        with:
          release: true
      - name: Build
        run: npm run build -- --define "SENTRY_DSN='${SENTRY_DSN}'" --define "SENTRY_RELEASE='${GITHUB_SHA}'"
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          release: ${{ github.sha }}
          sourcemaps: ./dist/control-center/browser
          set_commits: skip
      - name: Remove source maps
        run: find dist/control-center/browser -type f -name '*.map' -delete
      - name: Deploy image
        uses: valitydev/action-deploy-docker@v2
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build MatEz Library
        run: npm run build -- matez
      - name: Publish MatEz Library
        uses: valitydev/action-frontend/publish@v3
        with:
          directory: ./dist/matez
      # - name: Notify Mattermost
      #   uses: valitydev/action-mattermost-notify@v0
      #   with:
      #     webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
      #     channel: 'control-center'
      #     username: 'Frontend'
