name: Old Build
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init Thrift
        uses: valitydev/action-setup-thrift@v0.0.1

      - name: Init NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'
          cache: 'npm'

      - name: Install Packages
        run: npm ci

      - name: Compile Thrift
        run: npm run compile

      - name: Check & Build
        run: npm run ci:build